### ISSUE TITLE
Consider adding MIDI task group report reference

### ISSUE THREAD

**Issue by fedorov** [ftdc-picsl/fwCustomDeidentification#4]
Since you mention some of the relevant publications in the README, I thought you may want to be interested to read and reference this recent one as well:

> Clunie, D. A., Flanders, A., Taylor, A., Erickson, B., Bialecki, B., Brundage, D., Gutman, D., Prior, F., Seibert, J. A., Perry, J., Gichoya, J. W., Kirby, J., Andriole, K., Geneslaw, L., Moore, S., Fitzgerald, T. J., Tellis, W. & Xiao, Y. Report of the Medical Image De-Identification (MIDI) Task Group -- Best Practices and Recommendations. arXiv [cs.CR] (2023). at <http://arxiv.org/abs/2303.10473>

**Comment by cookpa** [comment]
Thanks, I'll do that

**Comment by cookpa** [comment]
Added to the README, this looks like a great resource. Thanks again

**Comment by fedorov** [comment]
> [MIDI group report] looks like a great resource

Kudos to David Clunie - cc'd @dclunie - I think he and the MIDI group will appreciate any feedback you might have about that document!
